/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.airline_project;

/**
 *
 * @author Piyush Verma
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Customer = new javax.swing.JMenu();
        AddCustMenuItem = new javax.swing.JMenuItem();
        SearchCustMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AddFlightMenuItem = new javax.swing.JMenuItem();
        BookFlightMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        ViewTicketMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        AddAdminMenuItm = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        Customer.setText("Customer");

        AddCustMenuItem.setText("Add Customer");
        AddCustMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustMenuItemActionPerformed(evt);
            }
        });
        Customer.add(AddCustMenuItem);

        SearchCustMenuItem.setText("Search Customer");
        SearchCustMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCustMenuItemActionPerformed(evt);
            }
        });
        Customer.add(SearchCustMenuItem);

        jMenuBar1.add(Customer);

        jMenu2.setText("Flights");

        AddFlightMenuItem.setText("Add Flight");
        AddFlightMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFlightMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(AddFlightMenuItem);

        BookFlightMenuItem.setText("Book Flight");
        BookFlightMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookFlightMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(BookFlightMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Tickets");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        ViewTicketMenuItem.setText("View Ticket");
        ViewTicketMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTicketMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(ViewTicketMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Admin");

        AddAdminMenuItm.setText("Add Admin");
        AddAdminMenuItm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAdminMenuItmActionPerformed(evt);
            }
        });
        jMenu3.add(AddAdminMenuItm);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Desktop)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Desktop)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddCustMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustMenuItemActionPerformed
        // TODO add your handling code here:
        AddCustomer customer = new AddCustomer(); //Creating object of AddCustomer IntFrame
        Desktop.add(customer); //Adding object to desktop pane
        customer.setVisible(true);
    }//GEN-LAST:event_AddCustMenuItemActionPerformed

    private void AddFlightMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFlightMenuItemActionPerformed
        // TODO add your handling code here:
        AddFlight flight = new AddFlight();
        Desktop.add(flight);
        flight.setVisible(true);
    }//GEN-LAST:event_AddFlightMenuItemActionPerformed

    private void AddAdminMenuItmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAdminMenuItmActionPerformed
        // TODO add your handling code here:
        AddAdmin admin = new AddAdmin();
        Desktop.add(admin);
        admin.setVisible(true);
    }//GEN-LAST:event_AddAdminMenuItmActionPerformed

    private void SearchCustMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCustMenuItemActionPerformed
        // TODO add your handling code here:
        SearchCustomer customer = new SearchCustomer();
        Desktop.add(customer);
        customer.setVisible(true);
    }//GEN-LAST:event_SearchCustMenuItemActionPerformed

    private void BookFlightMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookFlightMenuItemActionPerformed
        // TODO add your handling code here:
        BookFlight ticket = new BookFlight();
        Desktop.add(ticket);
        ticket.setVisible(true);
    }//GEN-LAST:event_BookFlightMenuItemActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void ViewTicketMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTicketMenuItemActionPerformed
        // TODO add your handling code here:
        ViewTicket ticket = new ViewTicket();
        Desktop.add(ticket);
        ticket.setVisible(true);
    }//GEN-LAST:event_ViewTicketMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddAdminMenuItm;
    private javax.swing.JMenuItem AddCustMenuItem;
    private javax.swing.JMenuItem AddFlightMenuItem;
    private javax.swing.JMenuItem BookFlightMenuItem;
    private javax.swing.JMenu Customer;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem SearchCustMenuItem;
    private javax.swing.JMenuItem ViewTicketMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
